### ISSUE TITLE
After save and reload every Tiberium storage is empty

### ISSUE THREAD

**Issue by Waldleufer** [RealTelefonmast/OfficialTiberiumRim#10]
### **Describe the bug**
  
After saving and reloading every Tiberium storage is empty

### **Describe your game setup**
  
1. - I installed TiberiumRim and then created a fresh colony
2. - Runnnig **only TiberiumRim Mod (and HugsLib + Harmony)** 
3. Playing with the following **DLCs enabled**
   - Rimworld - **Royalty**
   - Rimworld - **Ideology**

### **To Reproduce**
Steps to reproduce the behaviour:
1. Play with Tiberium Refinery running.
2. Observe the Tiberium storage filling up
    ![unknown](https://user-images.githubusercontent.com/22003632/150380007-014714e6-0212-4d55-b7d5-224fcfaa7744.png)
3. Save and reload.
4. All Tiberium Storage shows 0
    ![unknown](https://user-images.githubusercontent.com/22003632/150380029-79ef3a82-6de6-461d-a41d-4e466fc152b9.png)

### **HugsLib Errorlog** 
```diff
- A errorlog is still needed.
```
Please paste the link to your HugsLib ErrorLog here.
 1. Make sure you have [HugsLib](https://steamcommunity.com/sharedfiles/filedetails/?id=818773962) installed
 2. Freshly start Rimworld and reenact the steps until the bug.
 3. Press **Ctrl+F12** to automatically generate and publish an error log.
 4. Click on "Upload" then on "Copy" and then paste the link generated for you here.

### **Expected behavior**
- [ ] All Tiberium storage saving their state between game sessions.

### **Actual behavior**
Only saved during current game session.

**Comment by RealTelefonmast** [comment]
This has been fixed on the Experimental branch.
