### ISSUE TITLE
Reinforced Plates un-craftable

### ISSUE THREAD

**Issue by jojo935** [RealTelefonmast/OfficialTiberiumRim#14]
### Describe the bug

Whenever trying to craft Reinforced Plates at a GDI Factory, it shows as red and will not allow to be crafted for whatever reason. This locks out the whole GDI tech tree, so no weapons, no turrets, nothing. 

### Describe your game setup
Running the following mods:

[ModsConfig.txt](https://github.com/RealTelefonmast/OfficialTiberiumRim/files/8042161/ModsConfig.txt)

### Playing with the following DLCs enabled
        Rimworld - Royalty
        Rimworld - Ideology

### Steps to reproduce the behaviour:

Use the GDI Factory to produce Reinforced Plates under Bills. 

### HugsLib Errorlog

[Player.log](https://github.com/RealTelefonmast/OfficialTiberiumRim/files/8042200/Player.log)

### Expected behavior

It should be craftable. Without it craftable, it blocks out the whole GDI production tree. The turrets would be really useful...

### Actual behavior

Colonists will be unable to use and you cannot select as it is red. The plates will be uncraftable for whatever reason, so it locks out the GDI Armory.

Screenshots
![RimWorld Screenshot 2022 02 10 - 15 33 15 00](https://user-images.githubusercontent.com/41837068/153441030-f8041b28-bfea-461e-913a-577746c4dfb1.png)
![RimWorld Screenshot 2022 02 10 - 15 34 10 57](https://user-images.githubusercontent.com/41837068/153441172-2214b214-3bc4-4a80-a1e3-fb0f976e0e92.png)
![RimWorld Screenshot 2022 02 10 - 15 34 21 80](https://user-images.githubusercontent.com/41837068/153441181-34d59cba-2de5-4578-84fb-45683a4741be.png)

**Comment by Waldleufer** [comment]
Thank you for the detailed report!

**Comment by RealTelefonmast** [comment]
Issue has been fixed - TRecipes always created a NetworkBill instead of the vanilla Bill, even without a networkCost value, thus making it uncraftable.
