### ISSUE TITLE
Blossom orientation bug

### ISSUE THREAD

**Issue by Bonesters** [RealTelefonmast/OfficialTiberiumRim#5]
Blossoms seems to have every orientation except right-side up. Here's a screenshot to demonstrate the issue.
https://steamuserimages-a.akamaihd.net/ugc/1643216436139177321/2DBB7DE16FB787EA814960C716A9DF047C2EFE72/

**Comment by Waldleufer** [comment]
Is this still a thing? If not I'd suggest we close this.

**Comment by RealTelefonmast** [comment]
This has indeed been fixed already.
