### ISSUE TITLE
Ressource refineries are not working

### ISSUE THREAD

**Issue by Waldleufer** [RealTelefonmast/OfficialTiberiumRim#8]
### **Describe the bug**
  
Tiberium Ressource refinery is not working

### **Describe your game setup**
  
1. I installed TiberiumRim and then created a fresh colony
2. Running **only TiberiumRim Mod (and HugsLib + Harmony)** 
3. Playing with the following **DLCs enabled**
   - Rimworld - **Royalty**
   - Rimworld - **Ideology**

### **To Reproduce**
Steps to reproduce the behaviour:
1. Made a blank world with no to none mods. Just these basics
2. researched everything in dev mode and set up a basic infrastructure
3. so the harvesters are running and putting Tiberium in storage. Everything gets to get stored in the silos if they are here.
4. a bill is set up for the resource refinery

### **HugsLib Errorlog** 
![unknown](https://user-images.githubusercontent.com/22003632/150377758-45ae609e-3df7-40b3-a584-44854bf71f8a.png)
// A good Errorreport is still needed. Feel free to leave a comment with a link

### **Expected behavior**
- [ ] The bills at the refinery should yield resources.
- [ ] Pawns should be able to interact with the refinery

### **Actual behavior**
No resources are yielded, and no pawn can even interact with the refinery.

### **Screenshots**
![unknown](https://user-images.githubusercontent.com/22003632/150377446-68f4b286-d4ee-4918-b842-af4e1e5e82fd.png)
![unknown](https://user-images.githubusercontent.com/22003632/150377597-9cbbe63b-b4b2-49d6-a994-9d4b3cf2d2a7.png)
![unknown](https://user-images.githubusercontent.com/22003632/150377620-07f63365-e610-42f7-ba8e-7f60b07ab3e9.png)

Thank you Discord User Warhawk for submitting this report!

**Comment by RealTelefonmast** [comment]
The resource refinery is being completely reworked and will have a whole new functionality via using the new "chemical" system by collecting elemental resources via the centrifuge.
