### ISSUE TITLE
Harvesters not working after save and reload

### ISSUE THREAD

**Issue by Waldleufer** [RealTelefonmast/OfficialTiberiumRim#9]
### **Describe the bug**
  
Harvesters not working after save and reload

### **Describe your game setup**
  
1. I installed TiberiumRim and then created a fresh colony
2. Runnnig **only TiberiumRim Mod (and HugsLib + Harmony)** 
3. Playing with the following **DLCs enabled**
   - Rimworld - **Royalty**
   - Rimworld - **Ideology**

### **To Reproduce**
Steps to reproduce the behaviour:
1. Play with Tiberium Refinery running.
2. Save and reload.
3. All harvesters stopped working.

### **HugsLib Errorlog** 
```diff
- A errorlog is still needed.
```
Please paste the link to your HugsLib ErrorLog here.
 1. Make sure you have [HugsLib](https://steamcommunity.com/sharedfiles/filedetails/?id=818773962) installed
 2. Freshly start Rimworld and reenact the steps until the bug.
 3. Press **Ctrl+F12** to automatically generate and publish an error log.
 4. Click on "Upload" then on "Copy" and then paste the link generated for you here.

### **Expected behavior**
- [ ] After a reload the harvesters should resume their work.

### **Actual behavior**
All harvesters stopped working.

**Comment by RealTelefonmast** [comment]
This has been fixed alongside the emptied containers, the internal container instance was not saved correctly for harvesters.
